### ISSUE TITLE
Add DefaultBLLFactory to DI

### ISSUE THREAD

**Issue by NikitaEgorov** [Luxoft/BSSFramework#25]
I want to do it something like this

```csharp

public class Test
{
   public Test(IDefaultBllFactory bllFactory)
   {
      this.bll = bllFactory.Create<Employee>();
   }
}

```

**Comment by iatsuta** [comment]
1) В BLL.Core добавляешь новый интерфейс:

namespace SampleSystem.BLL
{
    public interface ISampleSystemDefaultBLLFactory : IDefaultBLLFactory<PersistentDomainObjectBase, Guid>
    {
    }
}
	
2) В BLL дописываешь его к существующей фабрике:

namespace SampleSystem.BLL
{
    public partial class SampleSystemDefaultBLLFactory : ISampleSystemDefaultBLLFactory
    {
    }
}

3) Регаешь интерфейс в DI:

...
                   .Self(SampleSystemSecurityServiceBase.Register)
                   .Self(SampleSystemBLLFactoryContainer.RegisterBLLFactory)

                   .AddScopedTransientByContainer<ISampleSystemDefaultBLLFactory>(container => new SampleSystemDefaultBLLFactory(container.MainContext));

4) Используешь:

namespace SampleSystem.BLL
{
    public partial class CountryBLL
    {
        // Manual BLL Constructor example. For configuration see BLLGeneratorConfiguration.cs
        public CountryBLL(
                ISampleSystemBLLContext context,
                ISecurityProvider<Country> securityProvider,
                ISampleSystemDefaultBLLFactory defaultBllFactory,
                ISpecificationEvaluator specificationEvaluator)
                : base(context, securityProvider, specificationEvaluator)
        {
            var employeeBLL = defaultBllFactory.Create<Employee>();
        }
    }
}
